import { REVIEW_STATUS } from "./logic";
import { ROLE_TEMPLATE_IDS, createRowsFromTemplate, getRoleTemplate, roleTemplates } from "./roleTemplates";

export const performanceTemplate = roleTemplates.map((template) => ({
  section: template.name,
  items: [
    ...template.dimensions.flatMap((dimension) => dimension.items),
    ...(template.adjustments ?? []),
  ],
}));

export const performanceFocusOptions = [
  { value: "all", label: "全部流程" },
  { value: "pending", label: "待处理" },
  { value: "archived", label: "已归档" },
  { value: "appeal", label: "申诉中" },
];

function createReview({
  id,
  employee,
  role,
  department,
  templateId,
  cycle = "2026-07",
  directLeader,
  indirectLeader,
  requiresSecondReview = true,
  status,
  values,
  templateHighlights,
  businessLines,
  feedbackStatus = "待反馈",
  committeeStatus = "待审批",
  appealStatus = "无申诉",
  owner,
  lastActionAt = "2026-07-08 09:00",
  operationLogs,
  comment,
  evidence,
}) {
  const template = getRoleTemplate(templateId);
  const targetIssued = status !== REVIEW_STATUS.targetIssue;
  const targetConfirmed = targetIssued && ![REVIEW_STATUS.employeeConfirm, REVIEW_STATUS.targetDispute].includes(status);

  return {
    id,
    employee,
    role,
    department,
    cycle,
    directLeader,
    indirectLeader,
    requiresSecondReview,
    status,
    owner: owner ?? directLeader,
    lastActionAt,
    lastActionName: operationLogs?.at(-1)?.action ?? "创建月度绩效任务",
    appealStatus,
    feedbackStatus,
    committeeStatus,
    roleTemplateId: templateId,
    roleTemplateName: template.name,
    businessLines: businessLines ?? template.businessLines ?? [],
    templateHighlights,
    sheetMeta: `花名：${employee} / 部门：内容经营中心 / ${department} / 岗位：${role}`,
    rows: createRowsFromTemplate(templateId, values),
    version: 1,
    activeTargetVersion: targetConfirmed ? 1 : null,
    pendingTargetVersion: targetIssued && !targetConfirmed ? 1 : null,
    targetVersions: targetIssued ? [{ version: 1, status: targetConfirmed ? "已生效" : "待员工确认", targets: createRowsFromTemplate(templateId, values), operator: directLeader, actedAt: lastActionAt, changeReason: "首次下发" }] : [],
    operationLogs: operationLogs ?? [
      {
        id: `${id}-log-1`,
        action: "创建月度绩效任务",
        operator: "系统",
        actedAt: lastActionAt,
        note: `${template.name}模板已绑定，等待上级下发。`,
        fromStatus: "未创建",
        toStatus: status,
      },
    ],
    comment,
    evidence,
  };
}

export const reviewsSeed = [
  createReview({
    id: "rv-editor-1",
    employee: "张小北",
    role: "中级剪辑师",
    department: "剪辑中心",
    templateId: ROLE_TEMPLATE_IDS.editor,
    directLeader: "江晚",
    indirectLeader: "磊姐",
    status: REVIEW_STATUS.targetIssue,
    owner: "江晚",
    templateHighlights: [
      { label: "剪辑产出", value: "46 条" },
      { label: "一次通过", value: "88%" },
      { label: "延期", value: "1 次" },
      { label: "证明材料", value: "待上传" },
    ],
    values: {
      editOutput: { selfText: "完成短剧正片剪辑 18 集、高光素材 28 条。", firstScore: 84, secondScore: 82 },
      editQuality: { selfText: "本月返修 3 次，一次通过率 88%。", firstScore: 80, secondScore: 78 },
      editEfficiency: { selfText: "多数任务按时交付，1 个版本因素材补充延期。", firstScore: 78, secondScore: 76 },
      editAsset: { selfText: "沉淀高光开头 3 秒节奏模板。", firstScore: 2, secondScore: 1 },
    },
    comment: "产出稳定，待下发后员工确认目标。",
    evidence: "剪辑交付记录、审核反馈、任务截止记录。",
  }),
  createReview({
    id: "rv-screenwriter-1",
    employee: "周编剧",
    role: "中级编剧",
    department: "编剧中心",
    templateId: ROLE_TEMPLATE_IDS.screenwriter,
    requiresSecondReview: false,
    directLeader: "李晓言",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.employeeConfirm,
    owner: "周编剧",
    templateHighlights: [
      { label: "剧本提交", value: "42 集" },
      { label: "重大返修", value: "1 次" },
      { label: "初审通过", value: "86%" },
      { label: "确认截止", value: "07-09" },
    ],
    values: {
      scriptQuality: { selfText: "主编初评 86 分，存在 1 次人物动机结构性返修。", firstScore: 78, secondScore: 76 },
      scriptOutput: { selfText: "完成短剧脚本 42 集，另补充 2 个项目大纲。", firstScore: 86, secondScore: 82 },
      scriptInnovation: { selfText: "沉淀一个可复用人物关系模板。", firstScore: 1, secondScore: 1 },
    },
    comment: "员工待确认本月绩效任务。",
    evidence: "剧本提交记录、审稿意见、项目推进表。",
  }),
  createReview({
    id: "rv-producer-1",
    employee: "林制片",
    role: "中级制片",
    department: "制片中心",
    templateId: ROLE_TEMPLATE_IDS.producer,
    directLeader: "江晚",
    indirectLeader: "磊姐",
    status: REVIEW_STATUS.resultEntry,
    owner: "林制片",
    templateHighlights: [
      { label: "项目管理", value: "5 个" },
      { label: "节点按时", value: "92%" },
      { label: "选题提报", value: "12 个" },
      { label: "执行问题", value: "2 次" },
    ],
    values: {
      producerQuality: { selfText: "选题评审通过 8 个，成片问题 1 次，项目执行问题 2 次。", firstScore: 82, secondScore: 80 },
      producerEfficiency: { selfText: "5 个项目节点按时率 92%，1 个运营确认节点延期。", firstScore: 80, secondScore: 78 },
      producerWorkload: { selfText: "本月提报选题 12 个，跟进项目管理 5 个。", firstScore: 84, secondScore: 82 },
      producerRisk: { selfText: "提前识别拍摄资源冲突并完成排期调整。", firstScore: 2, secondScore: 1 },
    },
    comment: "员工已进入结果录入阶段，需补齐附件证明。",
    evidence: "项目统筹表、选题登记表、评审记录。",
  }),
  createReview({
    id: "rv-editor-lead-1",
    employee: "陈组长",
    role: "剪辑组长",
    department: "剪辑中心",
    templateId: ROLE_TEMPLATE_IDS.editorLead,
    directLeader: "江晚",
    indirectLeader: "磊姐",
    status: REVIEW_STATUS.firstReview,
    owner: "江晚",
    templateHighlights: [
      { label: "组内任务", value: "128 条" },
      { label: "返修率", value: "7%" },
      { label: "带教", value: "2 人" },
      { label: "待评分", value: "一级" },
    ],
    values: {
      teamEditOutput: { selfText: "个人与组内任务均按月度计划完成，组内完成 128 条。", firstScore: 82, secondScore: 78 },
      teamEditQuality: { selfText: "组内返修率 7%，重大问题 0 次。", firstScore: 84, secondScore: 80 },
      teamEditEfficiency: { selfText: "重点项目排期稳定，临时需求当天响应。", firstScore: 82, secondScore: 78 },
      teamEditEnablement: { selfText: "输出通用素材命名规范并带教 2 名新人。", firstScore: 3, secondScore: 2 },
    },
    comment: "等待一级负责人逐项评分。",
    evidence: "组内任务记录、审核记录、带教材料。",
  }),
  createReview({
    id: "rv-traffic-1",
    employee: "许投流",
    role: "中级投流师",
    department: "运营增长中心",
    templateId: ROLE_TEMPLATE_IDS.trafficOperator,
    directLeader: "赵启",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.secondReview,
    owner: "江晚",
    templateHighlights: [
      { label: "素材测试", value: "64 条" },
      { label: "复盘", value: "6 份" },
      { label: "响应", value: "当日" },
      { label: "待复核", value: "二级" },
    ],
    values: {
      trafficWorkload: { selfText: "处理投放任务 41 项，素材测试 64 条。", firstScore: 84, secondScore: 80 },
      trafficQuality: { selfText: "完成 6 份复盘，问题判断准确率较上月提升。", firstScore: 82, secondScore: 78 },
      trafficEfficiency: { selfText: "紧急投放需求均在当日响应。", firstScore: 86, secondScore: 82 },
      trafficIndependent: { selfText: "独立处理 2 次素材衰减问题。", firstScore: 2, secondScore: 1 },
    },
    comment: "一级评分已提交，等待二级负责人复核。",
    evidence: "工作平台记录、投放复盘材料、任务记录。",
  }),
  createReview({
    id: "rv-business-1",
    employee: "顾商务",
    role: "中级商务",
    department: "商务部",
    templateId: ROLE_TEMPLATE_IDS.businessMiddle,
    directLeader: "沈牧",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.hrReview,
    owner: "HR-唐宁",
    templateHighlights: [
      { label: "有效触达", value: "38 次" },
      { label: "深度沟通", value: "9 次" },
      { label: "资源入库", value: "6 项" },
      { label: "合同成交", value: "1 个" },
    ],
    values: {
      businessMiddleWorkload: { selfText: "剧本资源有效触达 22 次，承制资源触达 16 次，深度沟通 9 次。", firstScore: 86, secondScore: 84 },
      businessMiddleQuality: { selfText: "6 项意向资源入库，其中 2 项进入评审。", firstScore: 82, secondScore: 80 },
      businessMiddleDeal: { selfText: "完成 1 个合同成交，已上传合同审批截图。", firstScore: 5, secondScore: 5 },
    },
    comment: "进入 HR 复核，需核验合同证明和加分上限。",
    evidence: "资源触达记录、入库记录、合同审批证明。",
  }),
  createReview({
    id: "rv-domestic-1",
    employee: "陆运营",
    role: "国内切片运营",
    department: "运营增长中心",
    templateId: ROLE_TEMPLATE_IDS.domesticClipOperator,
    directLeader: "赵启",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.committeeApproval,
    owner: "CEO",
    committeeStatus: "待审批",
    templateHighlights: [
      { label: "日均发布", value: "36 条" },
      { label: "维护账号", value: "12 个" },
      { label: "异常", value: "1 项" },
      { label: "审批", value: "CEO" },
    ],
    values: {
      domesticWorkload: { selfText: "切片素材日均发布 36 条，维护账号 12 个。", firstScore: 84, secondScore: 82 },
      domesticQuality: { selfText: "通过人工导入和截图说明切片表现，1 个账号增长异常。", firstScore: 78, secondScore: 76 },
      domesticEfficiency: { selfText: "多账号并发发布稳定，异常处理平均 2 小时内响应。", firstScore: 82, secondScore: 80 },
      domesticAccountAsset: { selfText: "沉淀账号异常排查清单。", firstScore: 2, secondScore: 1 },
    },
    comment: "HR 已提交CEO审批。",
    evidence: "账号运营记录、人工导入表、截图附件、HR复核意见。",
  }),
  createReview({
    id: "rv-finished-1",
    employee: "罗运营",
    role: "成品剧运营",
    department: "运营增长中心",
    templateId: ROLE_TEMPLATE_IDS.finishedDramaOperator,
    directLeader: "赵启",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.feedback,
    owner: "赵启",
    feedbackStatus: "待面谈",
    committeeStatus: "已审批",
    templateHighlights: [
      { label: "上架数量", value: "18 部" },
      { label: "准确率", value: "97%" },
      { label: "返工", value: "1 次" },
      { label: "结果", value: "待发布反馈" },
    ],
    values: {
      finishedWorkload: { selfText: "完成上架任务 18 部。", firstScore: 82, secondScore: 80 },
      finishedQuality: { selfText: "上架信息准确率 97%，返工 1 次。", firstScore: 84, secondScore: 82 },
      finishedEfficiency: { selfText: "平均处理周期低于本月基准。", firstScore: 82, secondScore: 80 },
      finishedSupport: { selfText: "沉淀上架检查清单。", firstScore: 2, secondScore: 1 },
    },
    comment: "结果已审批，待负责人面谈反馈。",
    evidence: "上架记录、检查记录、面谈草稿。",
  }),
  createReview({
    id: "rv-appeal-1",
    employee: "何编导",
    role: "编导",
    department: "编剧中心",
    templateId: ROLE_TEMPLATE_IDS.director,
    directLeader: "李晓言",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.appealSubmitted,
    owner: "HR-唐宁",
    appealStatus: "待HR调查",
    committeeStatus: "已审批",
    templateHighlights: [
      { label: "分镜提交", value: "21 组" },
      { label: "协作反馈", value: "有争议" },
      { label: "申诉指标", value: "质量" },
      { label: "处理人", value: "HR" },
    ],
    values: {
      directorWorkload: { selfText: "完成分镜 21 组，参与 4 个项目。", firstScore: 80, secondScore: 78 },
      directorQuality: { selfText: "对协作方质量评价存在异议，已补充说明材料。", firstScore: 66, secondScore: 64 },
      directorCoordination: { selfText: "补齐现场沟通纪要。", firstScore: 0, secondScore: 0 },
    },
    comment: "员工对质量维度评分提出申诉。",
    evidence: "分镜登记表、协作反馈截图、申诉说明。",
  }),
  createReview({
    id: "rv-director-1",
    employee: "江晚",
    role: "内容运营中心总监",
    department: "内容运营中心",
    templateId: ROLE_TEMPLATE_IDS.contentDirector,
    directLeader: "磊姐",
    indirectLeader: "CEO",
    status: REVIEW_STATUS.archived,
    owner: "HR-唐宁",
    appealStatus: "无申诉",
    feedbackStatus: "已面谈",
    committeeStatus: "已审批",
    templateHighlights: [
      { label: "中心人数", value: "58 人" },
      { label: "归档", value: "完成" },
      { label: "异常", value: "3 项" },
      { label: "模板覆盖", value: "13 岗" },
    ],
    values: {
      directorResult: { selfText: "内容经营中心月度绩效流程完成，关键项目按期推进。", firstScore: 86, secondScore: 84 },
      directorProcess: { selfText: "推动异常台账、申诉协同和复盘归档。", firstScore: 84, secondScore: 82 },
      directorManagement: { selfText: "完成 13 个岗位模板初始化和评分说明。", firstScore: 88, secondScore: 86 },
      directorSpecial: { selfText: "组织完成第一阶段绩效流程试运行。", firstScore: 3, secondScore: 2 },
    },
    operationLogs: [
      {
        id: "rv-director-1-log-1",
        action: "创建月度绩效任务",
        operator: "HR-唐宁",
        actedAt: "2026-07-01 09:00",
        note: "内容运营中心总监模板已绑定。",
        fromStatus: "未创建",
        toStatus: REVIEW_STATUS.targetIssue,
      },
      {
        id: "rv-director-1-log-2",
        action: "结果归档",
        operator: "HR-唐宁",
        actedAt: "2026-07-08 09:20",
        note: "CEO审批通过，申诉期结束后归档。",
        fromStatus: REVIEW_STATUS.feedback,
        toStatus: REVIEW_STATUS.archived,
      },
    ],
    comment: "已完成归档，可作为一期流程样例。",
    evidence: "HR汇总表、CEO审批记录、归档日志。",
  }),
  createReview({
    id: "rv-screenwriter-dispute-1",
    employee: "魏编剧",
    role: "初级编剧",
    department: "编剧中心",
    templateId: ROLE_TEMPLATE_IDS.screenwriter,
    requiresSecondReview: false,
    directLeader: "李晓言",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.targetDispute,
    owner: "李晓言",
    lastActionAt: "2026-07-10 11:20",
    templateHighlights: [
      { label: "异议项目", value: "个人月度目标" },
      { label: "异议状态", value: "待Leader调整" },
      { label: "确认截止", value: "07-15" },
      { label: "目标版本", value: "V1" },
    ],
    values: {
      scriptQuality: { selfText: "希望将返修率口径调整为主编确认后的有效返修。", firstScore: 76, secondScore: 0 },
      scriptOutput: { selfText: "本月计划完成短剧脚本 24 集。", firstScore: 80, secondScore: 0 },
      scriptInnovation: { selfText: "计划沉淀人物冲突素材库。", firstScore: 0, secondScore: 0 },
    },
    operationLogs: [{ id: "rv-screenwriter-dispute-1-log-1", action: "提出绩效目标异议", operator: "魏编剧", actedAt: "2026-07-10 11:20", note: "个人月度目标的返修口径需要调整。", fromStatus: REVIEW_STATUS.employeeConfirm, toStatus: REVIEW_STATUS.targetDispute }],
    comment: "员工已提交目标异议，等待直属 Leader 调整并重新下发。",
    evidence: "目标异议说明、历史返修登记表。",
  }),
  createReview({
    id: "rv-editor-executing-1",
    employee: "沈剪辑",
    role: "高级剪辑师",
    department: "剪辑中心",
    templateId: ROLE_TEMPLATE_IDS.editor,
    directLeader: "周岚",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.executing,
    owner: "沈剪辑",
    lastActionAt: "2026-07-09 17:40",
    templateHighlights: [
      { label: "目标版本", value: "V1已生效" },
      { label: "本月重点", value: "爆点节奏优化" },
      { label: "进度", value: "执行中" },
      { label: "填报时间", value: "07-25起" },
    ],
    values: {
      editOutput: { selfText: "已完成首周 10 集粗剪及 16 条高光素材。", firstScore: 86, secondScore: 84 },
      editQuality: { selfText: "首轮审核通过率 90%，返修 1 次。", firstScore: 84, secondScore: 82 },
      editEfficiency: { selfText: "紧急素材平均当日响应。", firstScore: 86, secondScore: 84 },
      editAsset: { selfText: "正在沉淀开头节奏参考库。", firstScore: 1, secondScore: 1 },
    },
    operationLogs: [{ id: "rv-editor-executing-1-log-1", action: "确认绩效目标", operator: "沈剪辑", actedAt: "2026-07-09 17:40", note: "绩效目标V1已生效，当前处于执行期。", fromStatus: REVIEW_STATUS.employeeConfirm, toStatus: REVIEW_STATUS.executing }],
    comment: "目标已确认，尚未到结果填报节点。",
    evidence: "目标确认记录、首周交付台账。",
  }),
  createReview({
    id: "rv-producer-appeal-investigation-1",
    employee: "唐制片",
    role: "执行制片",
    department: "制片中心",
    templateId: ROLE_TEMPLATE_IDS.producer,
    directLeader: "林制片",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.appealInvestigation,
    owner: "HR-唐宁",
    appealStatus: "HR调查中",
    committeeStatus: "已审批",
    lastActionAt: "2026-07-11 15:10",
    templateHighlights: [
      { label: "申诉维度", value: "进度成本" },
      { label: "当前状态", value: "HR调查中" },
      { label: "补充材料", value: "3份" },
      { label: "原结果", value: "A" },
    ],
    values: {
      producerQuality: { selfText: "项目关键节点已完成，但成本偏差归因存在争议。", firstScore: 76, secondScore: 74 },
      producerEfficiency: { selfText: "核心节点按时率 88%，补充资源协调记录。", firstScore: 78, secondScore: 76 },
      producerWorkload: { selfText: "跟进 4 个项目，提交 9 份统筹记录。", firstScore: 82, secondScore: 80 },
      producerRisk: { selfText: "提前上报两项供应商风险。", firstScore: 1, secondScore: 1 },
    },
    operationLogs: [{ id: "rv-producer-appeal-investigation-1-log-1", action: "受理并调查申诉", operator: "HR-唐宁", actedAt: "2026-07-11 15:10", note: "已收集项目成本变动说明和领导评分依据。", fromStatus: REVIEW_STATUS.appealSubmitted, toStatus: REVIEW_STATUS.appealInvestigation }],
    comment: "HR正在核验成本偏差归因与原始评分依据。",
    evidence: "申诉材料、项目成本台账、评分记录。",
  }),
  createReview({
    id: "rv-business-appeal-ceo-1",
    employee: "郑商务",
    role: "初级商务",
    department: "商务部",
    templateId: ROLE_TEMPLATE_IDS.businessMiddle,
    directLeader: "沈牧",
    indirectLeader: "江晚",
    status: REVIEW_STATUS.appealInProgress,
    owner: "CEO",
    appealStatus: "待CEO裁决",
    committeeStatus: "已审批",
    lastActionAt: "2026-07-12 10:30",
    templateHighlights: [
      { label: "申诉维度", value: "资源质量" },
      { label: "调查结论", value: "已完成" },
      { label: "当前状态", value: "待CEO裁决" },
      { label: "原结果", value: "B" },
    ],
    values: {
      businessMiddleWorkload: { selfText: "完成资源触达 28 次，建立 5 个有效合作线索。", firstScore: 72, secondScore: 70 },
      businessMiddleQuality: { selfText: "补充了客户有效性证明，申请复核资源质量评分。", firstScore: 66, secondScore: 64 },
      businessMiddleDeal: { selfText: "完成 1 次意向合作推进。", firstScore: 1, secondScore: 1 },
    },
    operationLogs: [{ id: "rv-business-appeal-ceo-1-log-1", action: "提交申诉调查", operator: "HR-唐宁", actedAt: "2026-07-12 10:30", note: "HR调查完成，建议CEO结合补充证明裁决。", fromStatus: REVIEW_STATUS.appealInvestigation, toStatus: REVIEW_STATUS.appealInProgress }],
    comment: "等待CEO决定维持原结果或生成修正结果版本。",
    evidence: "客户沟通纪要、资源证明、HR调查记录。",
  }),
];
